#![windows_subsystem = "windows"]

#[cfg(windows)] use std::os::windows::process::CommandExt;
use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use jwalk::WalkDir;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use std::{fs, path::PathBuf, sync::{mpsc, Arc, RwLock}, thread, time::Instant};
use tao::{event::{Event, WindowEvent}, event_loop::{ControlFlow, EventLoopBuilder, EventLoopProxy}, window::WindowBuilder};
use wry::WebViewBuilder;
use usn_journal_rs::volume::Volume;

const HTML: &str = include_str!("ui.html");
#[derive(Clone, Serialize, Deserialize)] struct Entry { name:String, path:String, ext:String, folder:bool }
#[derive(Deserialize)] struct Command { action:String, query:Option<String>, path:Option<String>, kind:Option<String>, ext:Option<String>, drives:Option<Vec<String>>, limit:Option<usize>, sort:Option<String>, descending:Option<bool>, paths:Option<Vec<String>>, match_case:Option<bool>, whole_word:Option<bool>, match_path:Option<bool>, regex:Option<bool>, search_id:Option<u64> }
enum UiEvent { Eval(String) }
#[derive(Serialize)] struct Preview { path:String, name:String, kind:String, size:String, modified:String, content:String }


#[cfg(windows)]
fn is_elevated()->bool{std::process::Command::new("net").args(["session"]).creation_flags(0x08000000).output().map(|o|o.status.success()).unwrap_or(false)}
#[cfg(not(windows))]
fn is_elevated()->bool{false}
fn drives()->Vec<String>{(b'A'..=b'Z').map(|c|format!("{}:\\",c as char)).filter(|p|PathBuf::from(p).exists()).collect()}
fn js<T:Serialize>(name:&str,data:&T)->String{format!("window.{}({});",name,serde_json::to_string(data).unwrap_or("null".into()))}
fn cache_path()->PathBuf{dirs::data_local_dir().unwrap_or_else(std::env::temp_dir).join("AizenSearch").join("index.bin")}
fn save_cache(entries:&[Entry]){let p=cache_path();if let Some(d)=p.parent(){let _=fs::create_dir_all(d);}if let Ok(data)=bincode::serialize(entries){let tmp=p.with_extension("tmp");if fs::write(&tmp,data).is_ok(){let _=fs::rename(tmp,p);}}}
fn load_cache()->Vec<Entry>{fs::read(cache_path()).ok().and_then(|b|bincode::deserialize(&b).ok()).unwrap_or_default()}

fn mft_drive(root:&str)->Result<Vec<Entry>,String>{let letter=root.chars().next().ok_or("Missing drive letter")?;let volume=Volume::from_drive_letter(letter).map_err(|e|e.to_string())?;let mft=volume.mft();let mut resolver=volume.path_resolver_with_cache();let mut out=Vec::new();for result in mft.iter(){let record=match result{Ok(v)=>v,Err(_)=>continue};let Some(path)=resolver.resolve_path(&record) else{continue};let full=if path.is_absolute(){path}else{PathBuf::from(root).join(path)};let name=record.file_name.to_string_lossy().into_owned();if name.is_empty(){continue}let folder=record.is_dir();let ext=if folder{String::new()}else{full.extension().map(|x|x.to_string_lossy().to_lowercase()).unwrap_or_default()};out.push(Entry{name,path:full.to_string_lossy().into_owned(),ext,folder});}Ok(out)}
fn scan_drive(root:&str)->Vec<Entry>{let mut out=Vec::new();for item in WalkDir::new(root).skip_hidden(false).parallelism(jwalk::Parallelism::RayonNewPool(4)).into_iter().filter_map(Result::ok){let p=item.path();let name=item.file_name().to_string_lossy().into_owned();let folder=item.file_type().is_dir();let ext=if folder{String::new()}else{p.extension().map(|x|x.to_string_lossy().to_lowercase()).unwrap_or_default()};out.push(Entry{name,path:p.to_string_lossy().into_owned(),ext,folder});}out}
fn start_index(index:Arc<RwLock<Vec<Entry>>>,proxy:EventLoopProxy<UiEvent>,requested:Option<Vec<String>>){thread::spawn(move||{let roots=requested.filter(|x|!x.is_empty()).unwrap_or_else(drives);let started=Instant::now();let total_drives=roots.len();let begin=serde_json::json!({"drives":roots,"totalDrives":total_drives,"cachedCount":index.read().unwrap().len()});let _=proxy.send_event(UiEvent::Eval(js("indexStarted",&begin)));let(tx,rx)=mpsc::channel();for root in roots.clone(){let tx=tx.clone();thread::spawn(move||{let _=tx.send((root.clone(),"start".to_string(),Vec::new(),String::new()));match mft_drive(&root){Ok(entries)=>{let _=tx.send((root,"done".to_string(),entries,"MFT".to_string()));},Err(e)=>{let reason=e.to_string();let _=tx.send((root.clone(),"fallback".to_string(),Vec::new(),reason));let entries=scan_drive(&root);let _=tx.send((root,"done".to_string(),entries,"Deep scan".to_string()));}}});}drop(tx);let mut all=index.read().unwrap().clone();let mut engines=Vec::new();let mut completed=0usize;for(root,stage,mut entries,detail)in rx{match stage.as_str(){"start"=>{let p=serde_json::json!({"drive":root,"stage":"Reading NTFS metadata","completed":completed,"totalDrives":total_drives,"count":all.len(),"seconds":started.elapsed().as_secs_f32()});let _=proxy.send_event(UiEvent::Eval(js("indexDriveProgress",&p)));},"fallback"=>{let p=serde_json::json!({"drive":root,"stage":"MFT unavailable - deep scanning","detail":detail,"completed":completed,"totalDrives":total_drives,"count":all.len(),"seconds":started.elapsed().as_secs_f32()});let _=proxy.send_event(UiEvent::Eval(js("indexDriveProgress",&p)));},"done"=>{completed+=1;let prefix=root.to_lowercase();all.retain(|e|!e.path.to_lowercase().starts_with(&prefix));all.append(&mut entries);all.sort_unstable_by(|a,b|a.name.to_lowercase().cmp(&b.name.to_lowercase()));*index.write().unwrap()=all.clone();engines.push(format!("{} {}",root,detail));let p=serde_json::json!({"drive":root,"stage":"Complete - searchable now","engine":detail,"completed":completed,"totalDrives":total_drives,"count":all.len(),"seconds":started.elapsed().as_secs_f32()});let _=proxy.send_event(UiEvent::Eval(js("indexDriveProgress",&p)));},_=>{}}}all.sort_unstable_by(|a,b|a.name.to_lowercase().cmp(&b.name.to_lowercase()));save_cache(&all);let count=all.len();*index.write().unwrap()=all;let payload=serde_json::json!({"count":count,"seconds":started.elapsed().as_secs_f32(),"drives":roots,"engines":engines,"fresh":true});let _=proxy.send_event(UiEvent::Eval(js("indexReady",&payload)));});}

fn human_size(n:u64)->String{const U:[&str;5]=["B","KB","MB","GB","TB"];let mut v=n as f64;let mut i=0;while v>=1024.0&&i<4{v/=1024.0;i+=1}if i==0{format!("{} {}",n,U[i])}else{format!("{:.1} {}",v,U[i])}}
fn preview(path:&str)->Preview{let p=PathBuf::from(path);let name=p.file_name().map(|x|x.to_string_lossy().into_owned()).unwrap_or_else(||path.into());let meta=fs::metadata(&p).ok();let size=meta.as_ref().map(|m|if m.is_dir(){"Folder".into()}else{human_size(m.len())}).unwrap_or_else(||"Unavailable".into());let modified=meta.and_then(|m|m.modified().ok()).and_then(|t|t.duration_since(std::time::UNIX_EPOCH).ok()).map(|d|format!("{}",d.as_secs())).unwrap_or_default();let ext=p.extension().map(|x|x.to_string_lossy().to_lowercase()).unwrap_or_default();let mut kind="meta".to_string();let mut content=String::new();if ["png","jpg","jpeg","gif","webp","bmp","svg"].contains(&ext.as_str()){if let Ok(bytes)=fs::read(&p){if bytes.len()<=8*1024*1024{let mime=match ext.as_str(){"jpg"|"jpeg"=>"image/jpeg","gif"=>"image/gif","webp"=>"image/webp","bmp"=>"image/bmp","svg"=>"image/svg+xml",_=>"image/png"};kind="image".into();content=format!("data:{};base64,{}",mime,BASE64.encode(bytes));}}}else if ["txt","md","rs","py","js","ts","json","toml","yaml","yml","css","html","log","csv","xml","ini"].contains(&ext.as_str()){if let Ok(bytes)=fs::read(&p){let take=bytes.len().min(65536);content=String::from_utf8_lossy(&bytes[..take]).into_owned();kind="text".into();}}Preview{path:path.into(),name,kind,size,modified,content}}
fn extension_icons(paths:&[String])->std::collections::HashMap<String,String>{use std::collections::HashMap;let mut out=HashMap::new();let dir=std::env::temp_dir().join("aizen-icons");let _=fs::create_dir_all(&dir);for source in paths.iter().take(64){let p=PathBuf::from(source);let key=if p.is_dir(){"__folder__".to_string()}else{p.extension().map(|x|x.to_string_lossy().to_lowercase()).filter(|x|!x.is_empty()).unwrap_or_else(||"__file__".into())};if out.contains_key(&key){continue}let path=dir.join(format!("{}.png",key.replace(|c:char|!c.is_alphanumeric(),"_")));if !path.exists(){let sp=p.to_string_lossy().replace("'","''");let op=path.to_string_lossy().replace("'","''");let script=format!("Add-Type -AssemblyName System.Drawing; $i=[System.Drawing.Icon]::ExtractAssociatedIcon('{}'); if($i){{$b=$i.ToBitmap();$b.Save('{}',[System.Drawing.Imaging.ImageFormat]::Png);$b.Dispose();$i.Dispose()}}",sp,op);let _=std::process::Command::new("powershell").args(["-NoProfile","-NonInteractive","-WindowStyle","Hidden","-Command",&script]).creation_flags(0x08000000).output();}if let Ok(bytes)=fs::read(&path){out.insert(key,format!("data:image/png;base64,{}",BASE64.encode(bytes)));}}out}
fn search(index:&[Entry],q:&str,kind:&str,ext:&str,limit:usize,sort:&str,descending:bool,match_case:bool,whole_word:bool,match_path:bool,regex_mode:bool)->Vec<Entry>{
 let mut positives=Vec::<String>::new();let mut phrases=Vec::<String>::new();let mut excludes=Vec::<String>::new();let mut syntax_ext=String::new();let mut syntax_kind=kind.to_string();let mut force_path=false;
 let token_re=regex::Regex::new(r#"\"([^\"]+)\"|(\S+)"#).unwrap();
 for cap in token_re.captures_iter(q){let token=cap.get(1).or_else(||cap.get(2)).unwrap().as_str();let low=if match_case{token.to_string()}else{token.to_lowercase()};if cap.get(1).is_some(){phrases.push(low.clone())}if let Some(v)=low.strip_prefix("ext:"){syntax_ext=v.trim_start_matches('.').to_string();continue}if let Some(v)=low.strip_prefix("type:"){syntax_kind=match v{"file"|"files"=>"files","folder"|"folders"=>"folders",_=>kind}.to_string();continue}if let Some(v)=low.strip_prefix("path:"){force_path=true;if !v.is_empty(){positives.push(v.to_string())}continue}if let Some(v)=low.strip_prefix('!'){if !v.is_empty(){excludes.push(v.to_string())}continue}positives.push(low);}
 let clean=positives.join(" ");let effective_ext=if !syntax_ext.is_empty(){syntax_ext.as_str()}else{ext};
 if clean.trim().is_empty()&&excludes.is_empty()&&syntax_kind=="all"&&effective_ext.is_empty()&&sort=="name"&&!descending{return index.iter().take(limit.clamp(100,20000)).cloned().collect()}
 let needle=clean;let typed_suffix=needle.rsplit_once('.').and_then(|(base,suf)|if !base.is_empty()&&suf.len()<=10&&suf.chars().all(|c|c.is_alphanumeric()){Some((base.to_string(),suf.to_string()))}else{None});let search_text=typed_suffix.as_ref().map(|x|x.0.as_str()).unwrap_or(&needle);let terms:Vec<String>=search_text.split(|c:char|c.is_whitespace()||(!c.is_alphanumeric()&&c!='_'&&c!='-'&&c!='\\'&&c!=':')).filter(|x|!x.is_empty()).map(str::to_owned).collect();
 let wildcard=if !regex_mode&&(needle.contains('*')||needle.contains('?')){let pat=format!("^{}$",regex::escape(&needle).replace("\\*",".*").replace("\\?","."));regex::RegexBuilder::new(&pat).case_insensitive(!match_case).build().ok()}else{None};let regex=if regex_mode{regex::RegexBuilder::new(&needle).case_insensitive(!match_case).build().ok()}else{None};
 let mut out:Vec<Entry>=index.par_iter().filter(|e|{if syntax_kind=="files"&&e.folder{return false}if syntax_kind=="folders"&&!e.folder{return false}if !effective_ext.is_empty()&&(e.folder||e.ext!=effective_ext){return false}let raw=if force_path||match_path{format!("{} {}",e.name,e.path)}else{e.name.clone()};let hay=if match_case{raw}else{raw.to_lowercase()};if excludes.iter().any(|x|hay.contains(x)){return false}if phrases.iter().any(|x|!hay.contains(x)){return false}if let Some(r)=&regex{return r.is_match(&hay)}if let Some(r)=&wildcard{return r.is_match(&e.name)}if whole_word{return terms.iter().all(|w|hay.split(|c:char|!c.is_alphanumeric()&&c!='_').any(|part|part==w))}terms.iter().all(|w|hay.contains(w))}).cloned().collect();
 out.sort_unstable_by(|a,b|{let o=if sort=="name"{let score=|e:&Entry|{let n=e.name.to_lowercase();let stem=PathBuf::from(&e.name).file_stem().map(|x|x.to_string_lossy().to_lowercase()).unwrap_or_default();let relation=if n==needle{0}else if n.starts_with(search_text){1}else if stem.contains(search_text){2}else if e.path.to_lowercase().contains(search_text){3}else{4};let preferred=typed_suffix.as_ref().map(|x|if e.ext==x.1{0}else{1}).unwrap_or(0);let full_exact=if n==needle{0}else{1};(full_exact,preferred,relation,n.len(),n)};score(a).cmp(&score(b))}else{match sort{"type"=>a.ext.cmp(&b.ext),"path"=>a.path.cmp(&b.path),_=>a.name.to_lowercase().cmp(&b.name.to_lowercase())}};if descending{o.reverse()}else{o}});out.truncate(limit.clamp(100,20000));out
}

fn main(){let _single_instance=match std::net::TcpListener::bind("127.0.0.1:47651"){Ok(v)=>v,Err(_)=>return};
 let event_loop=EventLoopBuilder::<UiEvent>::with_user_event().build();let proxy=event_loop.create_proxy();
 let window=WindowBuilder::new().with_title("Aizen Search v0.3.0").with_inner_size(tao::dpi::LogicalSize::new(1380.0,840.0)).with_min_inner_size(tao::dpi::LogicalSize::new(1040.0,680.0)).build(&event_loop).unwrap();
 let index=Arc::new(RwLock::new(load_cache()));let cached=index.read().unwrap().len();
 let payload=serde_json::json!({"count":cached,"drives":drives(),"cached":cached>0,"elevated":is_elevated(),"engine":"MFT/USN with scan fallback"});
 let payload_json=serde_json::to_string(&payload).unwrap();
 let html=HTML.replace("__AIZEN_BOOT__",&payload_json);
 let idx=index.clone();let ipc_proxy=proxy.clone();
 let webview=WebViewBuilder::new().with_html(html).with_ipc_handler(move|msg|{
  let raw=msg.body();
  match serde_json::from_str::<Command>(raw){Ok(cmd)=>match cmd.action.as_str(){
   "search"=>{let snapshot=idx.clone();let pxy=ipc_proxy.clone();let id=cmd.search_id.unwrap_or(0);let query=cmd.query.unwrap_or_default();let kind=cmd.kind.unwrap_or_else(||"all".into());let ext=cmd.ext.unwrap_or_default();let limit=cmd.limit.unwrap_or(5000).min(5000);let sort=cmd.sort.unwrap_or_else(||"name".into());let descending=cmd.descending.unwrap_or(false);let mc=cmd.match_case.unwrap_or(false);let ww=cmd.whole_word.unwrap_or(false);let mp=cmd.match_path.unwrap_or(true);let rx=cmd.regex.unwrap_or(false);thread::spawn(move||{let started=Instant::now();let results={let guard=snapshot.read().unwrap();search(&guard,&query,&kind,ext.trim_start_matches('.'),limit,&sort,descending,mc,ww,mp,rx)};let payload=serde_json::json!({"id":id,"items":results,"ms":started.elapsed().as_secs_f64()*1000.0});let _=pxy.send_event(UiEvent::Eval(js("showSearchResponse",&payload)));});},
   "open"=>if let Some(p)=cmd.path{let _=open::that(p);},
   "folder"=>if let Some(p)=cmd.path{if let Some(parent)=PathBuf::from(p).parent(){let _=open::that(parent);}},
   "copy"=>if let Some(p)=cmd.path{let escaped=p.replace("'","''");let _=std::process::Command::new("powershell").args(["-NoProfile","-WindowStyle","Hidden","-Command",&format!("Set-Clipboard -Value '{}'",escaped)]).creation_flags(0x08000000).spawn();},
   "copy_many"=>if let Some(paths)=cmd.paths{let joined=paths.join("\r\n");let escaped=joined.replace("'","''");let _=std::process::Command::new("powershell").args(["-NoProfile","-WindowStyle","Hidden","-Command",&format!("Set-Clipboard -Value '{}'",escaped)]).creation_flags(0x08000000).spawn();},
   "preview"=>if let Some(p)=cmd.path{let pxy=ipc_proxy.clone();thread::spawn(move||{let data=preview(&p);let _=pxy.send_event(UiEvent::Eval(js("showPreview",&data)));});},
   "icons"=>if let Some(paths)=cmd.paths{let pxy=ipc_proxy.clone();thread::spawn(move||{let data=extension_icons(&paths);let _=pxy.send_event(UiEvent::Eval(js("showIcons",&data)));});},
   "rebuild"=>start_index(idx.clone(),ipc_proxy.clone(),cmd.drives),
   "elevate"=>{if let Ok(exe)=std::env::current_exe(){if std::process::Command::new("powershell").args(["-NoProfile","-WindowStyle","Hidden","-Command",&format!("Start-Sleep -Milliseconds 700; Start-Process -FilePath '{}' -Verb RunAs",exe.display())]).creation_flags(0x08000000).spawn().is_ok(){std::process::exit(0);}}},_=>{}
  },Err(_)=>{}}
 }).build(&window).expect("WebView2 initialization failed");
 if cached==0{start_index(index.clone(),proxy.clone(),None);}
 event_loop.run(move|event,_,flow|{*flow=ControlFlow::Wait;match event{Event::UserEvent(UiEvent::Eval(s))=>{let _=webview.evaluate_script(&s);},Event::WindowEvent{event:WindowEvent::CloseRequested,..}=>*flow=ControlFlow::Exit,_=>{}}});
}

#[cfg(test)]mod tests{use super::*;fn e(name:&str,path:&str,ext:&str,folder:bool)->Entry{Entry{name:name.into(),path:path.into(),ext:ext.into(),folder}}
 #[test]fn disk_detection(){assert!(drives().iter().any(|d|d=="C:\\"));}
 #[test]fn filters(){let x=e("Main.rs",r"H:\src\Main.rs","rs",false);assert_eq!(search(&[x.clone()],"main","files","rs",5000,"name",false,false,false,true,false).len(),1);assert_eq!(search(&[x],"","folders","",5000,"name",false,false,false,true,false).len(),0);}
 #[test]fn extension_is_preference_not_filter(){let rows=vec![e("Cherax","C:\\Cherax","",true),e("CheraxLoader.exe","G:\\Cherax\\CheraxLoader.exe","exe",false),e("cherax.py","H:\\cherax.py","py",false)];let r=search(&rows,"cherax.exe","all","",100,"name",false,false,false,true,false);assert_eq!(r.len(),3);assert_eq!(r[0].name,"CheraxLoader.exe");assert!(r.iter().any(|x|x.ext=="py"));}
 #[test]fn exact_filename_first(){let rows=vec![e("main.rs.bak","C:\\main.rs.bak","bak",false),e("main.rs","H:\\main.rs","rs",false)];let r=search(&rows,"main.rs","all","",100,"name",false,false,false,true,false);assert_eq!(r[0].name,"main.rs");}
 #[test]fn empty_query_fast_sorted_slice(){let rows=vec![e("a","C:\\a","",false),e("b","C:\\b","",false)];let r=search(&rows,"","all","",100,"name",false,false,false,true,false);assert_eq!(r.len(),2);assert_eq!(r[0].name,"a");}
 #[test]fn query_syntax_ext_type_exclude_phrase(){let rows=vec![e("alpha script.py",r"H:\src\alpha script.py","py",false),e("alpha script.py",r"H:\node_modules\alpha script.py","py",false),e("alpha script.js",r"H:\src\alpha script.js","js",false),e("alpha script",r"H:\src\alpha script","",true)];let r=search(&rows,"ext:py type:file \"alpha script\" !node_modules","all","",100,"name",false,false,false,true,false);assert_eq!(r.len(),1);assert_eq!(r[0].ext,"py");assert!(!r[0].folder);}
 #[test]fn quoted_phrase_is_contiguous(){let rows=vec![e("alpha beta.txt",r"H:\alpha beta.txt","txt",false),e("alpha-x-beta.txt",r"H:\alpha-x-beta.txt","txt",false)];let r=search(&rows,"\"alpha beta\"","all","",100,"name",false,false,false,false,false);assert_eq!(r.len(),1);assert_eq!(r[0].name,"alpha beta.txt");}
 #[test]fn wildcard_search(){let rows=vec![e("cherax.exe",r"H:\cherax.exe","exe",false),e("cherax.txt",r"H:\cherax.txt","txt",false)];let r=search(&rows,"cherax*.exe","all","",100,"name",false,false,false,false,false);assert_eq!(r.len(),1);assert_eq!(r[0].ext,"exe");}
}